### PR TITLE
Fix a potential variable misuse bug

### PR DESCRIPTION
**Pull request by LostBenjamin**
Hi,

This pull request is a fix to a potential variable misuse bug at `pynestml/meta_model/ast_bit_operator.py`. Please check the changes.

Best,
Jingxuan

### CODE REVIEW

**Comment by pnbabu** [comment]
@LostBenjamin Thank you for your contribution! The changes look fine to me. I will let the CI run and approve your changes once everything looks green.

**Comment by pnbabu** [comment]
@LostBenjamin Before merging, you need to sign the [NEST Contributor agreement](https://nest-simulator.readthedocs.io/en/v3.3/contribute/index.html#contributing-to-nest) that asks for your details like name, affiliation, current position, etc. Could you please fill this out and send it to us? @heplesser

**Comment by heplesser** [comment]
@LostBenjamin Please send the NEST Contributor Agreement to info@nest-initiative.org.

**Comment by LostBenjamin** [comment]
sent.

**Review by pnbabu — APPROVED** [review]
Thank you!

**Pull request merged**
