### PR TITLE
Add support for installation via Docker

### PR DESCRIPTION
**Pull request by clinssen**
Draft PR, as we need to check with @steffengraber that NESTML works OK there.

### CODE REVIEW

**Comment by steffengraber** [comment]
@clinssen NESTML is included in the docker images that has NEST 3.1 and latest.

Please note the slightly changed usage of the images: https://github.com/nest/nest-docker

**Comment by clinssen** [comment]
@steffengraber: now that NESTML 5.0.0-rc1 is out, could I ask you to update to this version in the Docker images, so we can test whether everything works as expected? You will have to add the ``--pre`` flag to ``pip install``, because of the release candidate status.

**Comment by steffengraber** [comment]
@clinssen NESTML 5.0.0-rc1 is now included in our base image. This means that it is now also included in the images 3.2 (docker pull docker-registry.ebrains.eu/nest/nest-simulator:3.2) and dev (docker pull docker-registry.ebrains.eu/nest/nest-simulator:dev).

**Comment by clinssen** [comment]
Great, thank you!

**Review by pnbabu — APPROVED** [review]

**Pull request merged**
