### PR TITLE
Create nest Name objects for state and parameter variables

### LINKED ISSUE #625: RecordablesMap::insert_() should use nest::names instead of string
Upon instantiation of a generated C++ neuron class, the RecordablesMap is filled with entries, along the lines of:

```C++
RecordablesMap::insert_("V_m", &iaf_custom_nestml::get_V_m);
```

The fact that the recordable V_m is indexed by a string identifier ("V_m") causes issues with multithreading, because the RecordablesMap can only be copied thread-safely when elements are indexed by nest::names members, e.g.:

```C++
RecordablesMap::insert_(names::V_m, &iaf_custom_nestml::get_V_m);
```

To replace the strings with nest::names, a method is needed to dynamically (from the generated NESTML user module) insert elements into the nest::names namespace.

### PR DESCRIPTION
**Pull request by pnbabu**
Fixes #625 

The multithreading error is now solved by declaring all the `state` and `parameter` variables as `Name` objects inside the neuron and synapse header files. These `Name` objects are referenced wherever string equivalent of the variable names were used before.

### CODE REVIEW

**Comment by clinssen** [comment]
Great solution with the namespaces. Do the ``@nest::delay`` and ``@nest::weight`` annotations still function the same way as before?

**Comment by pnbabu** [comment]
@clinssen the `@nest::delay` and `@nest::weight` are untouched with the new changes as they are handled inside an if condition. However, the `names::` decorator was missing while handling `@nest::weight` variable which I have added now in this [commit](https://github.com/nest/nestml/pull/716/commits/24648644b3ce93018f7e44b65107ff878d822dcb)

**Comment by jougs** [comment]
I think this is the best solution for now, although I would prefer if we could get rid of `Name`s altogether as soon as possible...

One question: Shouldn't similar functionality also be added to the templates in `pynestml/codegeneration/resources_nest/point_neuron_nest2` and to the ones for the compartmental neurons added in #709?

**Comment by pnbabu** [comment]
@jougs the changes are added to templates in `pynestml/codegeneration/resources_nest/point_neuron/common` which are shared between the NEST 2.* and latest templates.

**Review by clinssen — APPROVED** [review]

**Review by jougs — APPROVED** [review]

**Pull request merged**
