### PR TITLE
Fix SpiNNaker figure and clean up "Running NESTML" documentation page

### PR DESCRIPTION
**Pull request by clinssen**
Preview: https://nestml-sandbox.readthedocs.io/en/latest/running/index.html

### CODE REVIEW

**Comment by pnbabu** [comment]
@clinssen thanks for adding these changes! The cards look good, but the SpiNNaker logo is too small to be visible on the card. Could you perhaps increase the size of the logo?

**Comment by clinssen** [comment]
It is fixed in this PR but will only be rendered once it is merged to the master branch.

**Comment by jessica-mitchell** [comment]
The image size needs to be scaled up for Spinnaker: 
image

**Review by jessica-mitchell — APPROVED** [review]
if the image will render fine then everything lgtm

**Comment by clinssen** [comment]
Thanks for the review!

**Pull request merged**
